
-- Table TCLIENTS
CREATE TABLE TCLIENTS (
  idClient INT IDENTITY(1,1) PRIMARY KEY,
  Nom VARCHAR(50),
  Prenom VARCHAR(50),
  CIN VARCHAR(20),
  Email VARCHAR(100),
  PhoneNumber VARCHAR(20),
  Ville VARCHAR(50),
  interdit BIT
);


-- Table TNOTIFFICATION_TYPE
CREATE TABLE TNOTIFFICATION_TYPE (
  IdType INT IDENTITY(1,1) PRIMARY KEY,
  NomType VARCHAR(50)
);


-- Table TLANGUES
CREATE TABLE TLANGUES (
  IdLangue INT IDENTITY(1,1) PRIMARY KEY,
  NomLangue VARCHAR(50)
);


-- Table TAUTHEURS
CREATE TABLE TAUTHEURS (
  IdAutheur INT IDENTITY(1,1) PRIMARY KEY,
  NomAutheur VARCHAR(50),
  PrenomAutheur VARCHAR(50)
);


-- Table TCATEGORIES
CREATE TABLE TCATEGORIES (
  idCategorie INT IDENTITY(1,1) PRIMARY KEY,
  NomCaterie VARCHAR(50)
);


-- Table TEDITEURS
CREATE TABLE TEDITEURS (
  IdEditeur INT IDENTITY(1,1) PRIMARY KEY,
  NomEditeur VARCHAR(50)
);


-- Table TLIVRES
CREATE TABLE TLIVRES (
  IdLivre INT IDENTITY(1,1) PRIMARY KEY,
  Titre VARCHAR(100),
  ISBN VARCHAR(20),
  IdLangue INT,
  IdAutheur INT,
  CONSTRAINT FK_LIVRES_LANGUE FOREIGN KEY (IdLangue)
      REFERENCES TLANGUES(IdLangue) ON DELETE CASCADE,
  CONSTRAINT FK_LIVRES_AUTHEUR FOREIGN KEY (IdAutheur)
      REFERENCES TAUTHEURS(IdAutheur) ON DELETE CASCADE
);


-- Table TEXEMPLAIRES
CREATE TABLE TEXEMPLAIRES (
  IdExemplaire INT IDENTITY(1,1) PRIMARY KEY,
  IdLivre INT,
  disponible BIT,
  localisation VARCHAR(100),
  CONSTRAINT FK_EXEMPLAIRES_LIVRES FOREIGN KEY (IdLivre)
      REFERENCES TLIVRES(IdLivre) ON DELETE CASCADE
);


-- Table TNOTIFICATIONS
CREATE TABLE TNOTIFICATIONS (
  IdNotification INT IDENTITY(1,1) PRIMARY KEY,
  IdClient INT,
  IdNotificationType INT,
  NotificationText NVARCHAR(MAX),
  NotificationDate DATETIME,
  CONSTRAINT FK_NOTIFICATIONS_CLIENT FOREIGN KEY (IdClient)
      REFERENCES TCLIENTS(idClient) ON DELETE CASCADE,
  CONSTRAINT FK_NOTIFICATIONS_TYPE FOREIGN KEY (IdNotificationType)
      REFERENCES TNOTIFFICATION_TYPE(IdType) ON DELETE CASCADE
);


-- Table TEMPRUNTS
CREATE TABLE TEMPRUNTS (
  IdEmprunt INT IDENTITY(1,1) PRIMARY KEY,
  IdClient INT,
  IdExemplaire INT,
  DateEmprunt DATETIME,
  DateRetour DATETIME,
  CONSTRAINT FK_EMPRUNTS_CLIENT FOREIGN KEY (IdClient)
      REFERENCES TCLIENTS(idClient) ON DELETE CASCADE,
  CONSTRAINT FK_EMPRUNTS_EXEMPLAIRE FOREIGN KEY (IdExemplaire)
      REFERENCES TEXEMPLAIRES(IdExemplaire) ON DELETE CASCADE
);


-- Table TRESERVATIONS
CREATE TABLE TRESERVATIONS (
  IdClient INT,
  IdLivre INT,
  DateReservation DATETIME,
  CONSTRAINT PK_TRESERVATIONS PRIMARY KEY (IdClient, IdLivre),
  CONSTRAINT FK_RESERVATIONS_CLIENT FOREIGN KEY (IdClient)
      REFERENCES TCLIENTS(idClient) ON DELETE CASCADE,
  CONSTRAINT FK_RESERVATIONS_LIVRE FOREIGN KEY (IdLivre)
      REFERENCES TLIVRES(IdLivre) ON DELETE CASCADE
);


-- Table TREVIEWS
CREATE TABLE TREVIEWS (
  IdReview INT IDENTITY(1,1) PRIMARY KEY,
  IdClient INT,
  IdLivre INT,
  review NVARCHAR(MAX),
  CONSTRAINT FK_REVIEWS_CLIENT FOREIGN KEY (IdClient)
      REFERENCES TCLIENTS(idClient) ON DELETE CASCADE,
  CONSTRAINT FK_REVIEWS_LIVRE FOREIGN KEY (IdLivre)
      REFERENCES TLIVRES(IdLivre) ON DELETE CASCADE
);


-- Table TAUTHEURS_LIVRES
CREATE TABLE TAUTHEURS_LIVRES (
  IdAutheur INT,
  IdLivre INT,
  CONSTRAINT PK_TAUTHEURS_LIVRES PRIMARY KEY (IdAutheur, IdLivre),
  CONSTRAINT FK_AUTHEURS_LIVRES_AUTHEUR FOREIGN KEY (IdAutheur)
      REFERENCES TAUTHEURS(IdAutheur) ON DELETE CASCADE,
  CONSTRAINT FK_AUTHEURS_LIVRES_LIVRES FOREIGN KEY (IdLivre)
      REFERENCES TLIVRES(IdLivre)
);


-- Table TCATEGORIES_LIVRES
CREATE TABLE TCATEGORIES_LIVRES (
  idCategorie INT,
  IdLivre INT,
  CONSTRAINT PK_TCATEGORIES_LIVRES PRIMARY KEY (idCategorie, IdLivre),
  CONSTRAINT FK_CATERIES_LIVRES_CATERIE FOREIGN KEY (idCategorie)
      REFERENCES TCATEGORIES(idCategorie) ON DELETE CASCADE,
  CONSTRAINT FK_CATERIES_LIVRES_LIVRE FOREIGN KEY (IdLivre)
      REFERENCES TLIVRES(IdLivre)
);


-- Table TEDITEURS_LIVRES
CREATE TABLE TEDITEURS_LIVRES (
  IdEditeur INT,
  IdLivre INT,
  CONSTRAINT PK_TEDITEURS_LIVRES PRIMARY KEY (IdEditeur, IdLivre),
  CONSTRAINT FK_DITEURS_LIVRES_EDITEUR FOREIGN KEY (IdEditeur)
      REFERENCES TEDITEURS(IdEditeur) ON DELETE CASCADE,
  CONSTRAINT FK_DITEURS_LIVRES_LIVRE FOREIGN KEY (IdLivre)
      REFERENCES TLIVRES(IdLivre)
);

